// This file is automatically generated. Please do not modify it manually.

/** Type definition for available 'other' codes */
export type OtherCode = 'checkered' | 'chequered' | 'earth' | 'jolly_roger' | 'klingon' | 'lgbt' | 'lgbt-progress' | 'lgbt-transgender' | 'mars' | 'nato' | 'olympics' | 'pirate' | 'un' | 'united_nations';

/** List of available 'other' codes (Array) */
export const OTHER_CODES: OtherCode[] = [
  'checkered',
  'chequered',
  'earth',
  'jolly_roger',
  'klingon',
  'lgbt',
  'lgbt-progress',
  'lgbt-transgender',
  'mars',
  'nato',
  'olympics',
  'pirate',
  'un',
  'united_nations',
];

/** Asset mapping for 'other' codes */
export const other: Record<OtherCode, any> = {
  "checkered": require("./other/CheckeredFlag/checkered.webp"),
  "chequered": require("./other/ChequeredFlag/chequered.webp"),
  "earth": require("./other/EarthFlag/earth.webp"),
  "jolly_roger": require("./other/JollyRogerFlag/jolly_roger.webp"),
  "klingon": require("./other/KlingonFlag/klingon.webp"),
  "lgbt": require("./other/LgbtFlag/lgbt.webp"),
  "lgbt-progress": require("./other/LgbtProgressFlag/lgbt-progress.webp"),
  "lgbt-transgender": require("./other/LgbtTransgenderFlag/lgbt-transgender.webp"),
  "mars": require("./other/MarsFlag/mars.webp"),
  "nato": require("./other/NatoFlag/nato.webp"),
  "olympics": require("./other/OlympicsFlag/olympics.webp"),
  "pirate": require("./other/PirateFlag/pirate.webp"),
  "un": require("./other/UnFlag/un.webp"),
  "united_nations": require("./other/UnitedNationsFlag/united_nations.webp"),
};
