// This file is automatically generated. Please do not modify it manually.
import { CircleFlag, type CircleFlagProps } from './CircleFlag';

/** Type definition for available 'other' codes */
export type OtherCode =
  | 'checkered'
  | 'chequered'
  | 'earth'
  | 'jolly_roger'
  | 'klingon'
  | 'lgbt'
  | 'lgbt-progress'
  | 'lgbt-transgender'
  | 'mars'
  | 'nato'
  | 'olympics'
  | 'pirate'
  | 'un'
  | 'united_nations';

/** List of available 'other' codes (Array) */
export const OTHER_CODES: OtherCode[] = [
  'checkered',
  'chequered',
  'earth',
  'jolly_roger',
  'klingon',
  'lgbt',
  'lgbt-progress',
  'lgbt-transgender',
  'mars',
  'nato',
  'olympics',
  'pirate',
  'un',
  'united_nations',
];

/** Asset mapping for 'other' codes */
export const OtherFlagSources: Record<OtherCode, any> = {
  'checkered': require('./other/checkered-flag/checkered.webp'),
  'chequered': require('./other/chequered-flag/chequered.webp'),
  'earth': require('./other/earth-flag/earth.webp'),
  'jolly_roger': require('./other/jolly_roger-flag/jolly_roger.webp'),
  'klingon': require('./other/klingon-flag/klingon.webp'),
  'lgbt': require('./other/lgbt-flag/lgbt.webp'),
  'lgbt-progress': require('./other/lgbt-progress-flag/lgbt-progress.webp'),
  'lgbt-transgender': require('./other/lgbt-transgender-flag/lgbt-transgender.webp'),
  'mars': require('./other/mars-flag/mars.webp'),
  'nato': require('./other/nato-flag/nato.webp'),
  'olympics': require('./other/olympics-flag/olympics.webp'),
  'pirate': require('./other/pirate-flag/pirate.webp'),
  'un': require('./other/un-flag/un.webp'),
  'united_nations': require('./other/united_nations-flag/united_nations.webp'),
};

export interface CircleOtherFlagProps extends Omit<CircleFlagProps, 'source'> {
  code: OtherCode;
}

export default function CircleOtherFlag({
  code,
  ...rest
}: CircleOtherFlagProps) {
  return <CircleFlag source={OtherFlagSources[code]} {...rest} />;
}
